### ISSUE TITLE
gui: bytearray error - can't convert 0xfe to utf-8

### ISSUE THREAD

**Issue by calculuswhiz** [scanmem/scanmem#120]
Hi, again.
I'm getting an error in GameConqueror when I scan bytecodes. It says:
```
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 947, in data_worker
    new_value = self.read_value(addr, TYPENAMES_S2G[scanmem_type.split(' ', 1)[0]], cur_value)
  File "/usr/share/gameconqueror/GameConqueror.py", line 974, in read_value
    return self.bytes2value(typestr, self.read_memory(addr, self.get_type_size(typestr, prev_value)))
  File "/usr/share/gameconqueror/GameConqueror.py", line 689, in bytes2value
    databytes = databytes.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```
Strings work fine now, though, which is good.

**Comment by sriemer** [comment]
Sounds familiar. Need to replace all .decode() calls with u() calls like already done for the hexview.

**Comment by sriemer** [comment]
Please test the code from PR #121 as well.

**Comment by sriemer** [comment]
The fix has been merged.

**Comment by calculuswhiz** [comment]
Works great! Thanks.
