### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_long_property'

### ISSUE THREAD

**Issue by ignatenkobrain** [scanmem/scanmem#144]
```python
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 1024, in <module>
    GameConqueror().main()
  File "/usr/share/gameconqueror/GameConqueror.py", line 106, in __init__
    Gtk.Settings.get_default().set_long_property('gtk-tooltip-timeout', 0, '')
AttributeError: 'NoneType' object has no attribute 'set_long_property'
```

**Comment by sriemer** [comment]
Thanks for reporting!

From https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Settings.html#Gtk.Settings:
````
Deprecated since version 3.16: Use GObject.Object.set () instead.
````

**Comment by sriemer** [comment]
Could you please test if the following works?
```python
Gtk.Settings.get_default().set_property('gtk-tooltip-timeout', 0)
```

**Comment by sriemer** [comment]
I've played around with this whole stuff and I've noticed that it has absolutely no effect.

From https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-tooltip-timeout:
````
GtkSettings:gtk-tooltip-timeout has been deprecated since version 3.10 and
should not be used in newly-written code.

This setting is ignored.
````
So we can remove that whole line.

**Comment by sriemer** [comment]
The fix is committed. So closing.
