### ISSUE TITLE
gui: Searching for the string `\\\` breaks the gui

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#172]
This only happens if some results are found.

```
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 971, in data_worker
    new_value = self.read_value(addr, TYPENAMES_S2G[scanmem_type.split(' ', 1)[0]], cur_value)
  File "/usr/share/gameconqueror/GameConqueror.py", line 998, in read_value
    return self.bytes2value(typestr, self.read_memory(addr, self.get_type_size(typestr, prev_value)))
  File "/usr/share/gameconqueror/GameConqueror.py", line 695, in get_type_size
    return len(eval('\''+value+'\''))
  File "<string>", line 1
    '\\\'
        ^
SyntaxError: EOL while scanning string literal
```

Searching for `\` or `\\` is fine, any more than 3 and everything breaks.

**Comment by sriemer** [comment]
Next time please write the exact steps how to reproduce this.
I've reproduced it with scan data type `string` and searching for `\\\` twice with my favourite simple reference game Chromium B.S.U. (`chromium-bsu`).

**Comment by sriemer** [comment]
The solution looks like this:
```python
diff --git a/gui/GameConqueror.py b/gui/GameConqueror.py
index f423c78..01c0718 100644
--- a/gui/GameConqueror.py
+++ b/gui/GameConqueror.py
@@ -692,7 +692,10 @@ class GameConqueror():
         elif typename == 'bytearray':
             return (len(value.strip())+1)/3
         elif typename == 'string':
-            return len(eval('\''+value+'\''))
+            try:
+                return len(eval('\''+value+'\''))
+            except:
+                return len(value)
         return None
 
     # parse bytes dumped by scanmem into number, string, etc.
```

If searching for `\\\`, then len 3 is returned. The search finds `\\\\\\` as this is using `\\` to represent one `\`. Changing `\\\\\\` to `+++` results in 3 bytes replaced from '\' to '+'.
Does this work for you as well?

**Comment by sriemer** [comment]
Hmm, this is hard to differentiate for the user from really entering `\\\\\\`. At least it doesn't crash any more. I've searched for `\\\\\\` in `chromium-bsu` and there is a single result for it.

**Comment by 12345ieee** [comment]
I just needed to search once to crash GC, the crash happened in the routine that updates the checks the values. Sorry for the incomplete bug report.

I confirm everything you said, GC works and replaces values correctly.

The only annoyance left is that the 'Value' column shows a single `\` as `\\`, which can be fixed (visually) by another terrible hack:

``` diff
diff --git a/gui/GameConqueror.py b/gui/GameConqueror.py
index f423c78..178f1cf 100644
--- a/gui/GameConqueror.py
+++ b/gui/GameConqueror.py
@@ -692,7 +692,10 @@ class GameConqueror():
         elif typename == 'bytearray':
             return (len(value.strip())+1)/3
         elif typename == 'string':
-            return len(eval('\''+value+'\''))
+            try:
+                return len(eval('\''+value+'\''))
+            except:
+                return len(value)
         return None
 
     # parse bytes dumped by scanmem into number, string, etc.
@@ -970,7 +973,7 @@ class GameConqueror():
                 if valid:
                     new_value = self.read_value(addr, TYPENAMES_S2G[scanmem_type.split(' ', 1)[0]], cur_value)
                     if new_value is not None:
-                        row[1] = str(new_value)
+                        row[1] = str(new_value).replace('\\\\', '\\')
                     else:
                         row[1] = '??'
                         row[3] = False
@@ -986,7 +989,7 @@ class GameConqueror():
                     if newvalue is None:
                         self.cheatlist_liststore[i] = (lockflag, False, desc, addr, typestr, '??', False)
                     elif newvalue != value and not self.cheatlist_editing:
-                        self.cheatlist_liststore[i] = (lockflag, locked, desc, addr, typestr, str(newvalue), valid)
+                        self.cheatlist_liststore[i] = (lockflag, locked, desc, addr, typestr, str(newvalue).replace('\\\\', '\\'), valid)
             self.is_data_worker_working = False
 
             Gdk.flush()
```

This mess definitely warrants a big nice comment in the code.

**Comment by 12345ieee** [comment]
No, damn, my previous change breaks for `\\\\`, which incorrectly becomes `\\`

**Comment by 12345ieee** [comment]
Ok, I should have a decent solution, works correctly against all the backslashes I could think of (and normal strings, too).

Sadly I have no idea of what the rationale for the `repr`/`eval` combination was, but I'm pretty happy about getting rid of `eval`-ing the input, to avoid injections (not that a GC injection is a security risk, but still...).

``` diff
diff --git a/gui/GameConqueror.py b/gui/GameConqueror.py
index 7dec2a4..a149087 100644
--- a/gui/GameConqueror.py
+++ b/gui/GameConqueror.py
@@ -705,7 +705,7 @@ class GameConqueror():
         elif typename == 'bytearray':
             return (len(value.strip())+1)/3
         elif typename == 'string':
-            return len(eval('\''+value+'\''))
+            return len(value)
         return None
 
     # parse bytes dumped by scanmem into number, string, etc.
@@ -715,8 +715,7 @@ class GameConqueror():
         if typename in TYPENAMES_G2STRUCT:
             return struct.unpack(TYPENAMES_G2STRUCT[typename], databytes)[0]
         elif typename == 'string':
-            databytes = str(u(databytes))
-            return repr('%s'%(databytes,))[1:-1]
+            return str(u(databytes))
         elif typename == 'bytearray':
             databytes = u(databytes)
             return ' '.join(['%02x'%ord(i) for i in databytes])
```

By the way, I attach to a text editor to test string scanning, because it's easy to build peculiar strings matched once and to verify things worked.

**Comment by sriemer** [comment]
This is also not good. I've found that storing the initial value `v` coming from libscanmem with `replace('\\', '\\\\')` fixes the issue but results in ugly displaying. So the solution is to convert the string value when reading from the tree views and converting back when storing to the tree views again.

Looks like this:
```diff
diff --git a/gui/GameConqueror.py b/gui/GameConqueror.py
index f423c78..449a8da 100644
--- a/gui/GameConqueror.py
+++ b/gui/GameConqueror.py
@@ -968,9 +968,14 @@ class GameConqueror():
                 row = self.scanresult_liststore[i]
                 addr, cur_value, scanmem_type, valid, off, rtype = row
                 if valid:
+                    if scanmem_type == 'string':
+                        cur_value = str(cur_value).replace('\\', '\\\\')
                     new_value = self.read_value(addr, TYPENAMES_S2G[scanmem_type.split(' ', 1)[0]], cur_value)
                     if new_value is not None:
-                        row[1] = str(new_value)
+                        if scanmem_type == 'string':
+                            row[1] = str(new_value).replace('\\\\', '\\')
+                        else:
+                            row[1] = str(new_value)
                     else:
                         row[1] = '??'
                         row[3] = False
@@ -982,10 +987,14 @@ class GameConqueror():
             for i in rows:
                 lockflag, locked, desc, addr, typestr, value, valid = self.cheatlist_liststore[i]
                 if valid and not locked:
+                    if typestr == 'string':
+                        value = str(value).replace('\\', '\\\\')
                     newvalue = self.read_value(addr, typestr, value)
                     if newvalue is None:
                         self.cheatlist_liststore[i] = (lockflag, False, desc, addr, typestr, '??', False)
                     elif newvalue != value and not self.cheatlist_editing:
+                        if typestr == 'string':
+                            newvalue = str(newvalue).replace('\\\\', '\\')
                         self.cheatlist_liststore[i] = (lockflag, locked, desc, addr, typestr, str(newvalue), valid)
             self.is_data_worker_working = False
 
```

**Comment by 12345ieee** [comment]
I can see this working, but why exactly do we need the repr/eval combo? What fails with my last patch?

**Comment by sriemer** [comment]
Sorry, I didn't notice that your last patch also fixes the issue completely. Your patch is better. Please provide it in a PR so that I can apply it.

**Comment by sriemer** [comment]
Both of our patches fail with Python 3. :disappointed:

**Comment by 12345ieee** [comment]
Sigh...

You can find me at \#ihatebackslashes on freenode.net, talking this way is pretty silly.

Python3 without patch fails in a vary spectacular way, though, I'm having a look...

**Comment by 12345ieee** [comment]
@sriemer , why cannot we keep it as simple as:

``` diff
diff --git a/gui/GameConqueror.py b/gui/GameConqueror.py
index 7dec2a4..a149087 100644
--- a/gui/GameConqueror.py
+++ b/gui/GameConqueror.py
@@ -705,7 +705,7 @@ class GameConqueror():
         elif typename == 'bytearray':
             return (len(value.strip())+1)/3
         elif typename == 'string':
-            return len(eval('\''+value+'\''))
+            return len(value)
         return None
 
     # parse bytes dumped by scanmem into number, string, etc.
@@ -715,8 +715,7 @@ class GameConqueror():
         if typename in TYPENAMES_G2STRUCT:
             return struct.unpack(TYPENAMES_G2STRUCT[typename], databytes)[0]
         elif typename == 'string':
-            databytes = str(u(databytes))
-            return repr('%s'%(databytes,))[1:-1]
+            return str(u(databytes))
         elif typename == 'bytearray':
             databytes = u(databytes)
             return ' '.join(['%02x'%ord(i) for i in databytes])
diff --git a/gui/misc.py b/gui/misc.py
index f923bce..b0f48aa 100644
--- a/gui/misc.py
+++ b/gui/misc.py
@@ -180,6 +180,6 @@ def menu_append_item(menu, name, callback, data):
 # for Python 3: convert to unicode just like Python 2 does
 def u(x):
     if PY3K:
-        return codecs.unicode_escape_decode(x)[0]
+        return codecs.decode(x, errors='ignore')
     else:
         return x
```

Commit c2326d70951611927b2a6ce270b0734edc28b6a6 isn't extremely clear on why `unicode_escape_decode` is needed.

**Comment by sriemer** [comment]
`.decode()` defaults to `utf-8` and doesn't cover special bytes like `0xfe` in byte array search or for the data in the hex view.

**Comment by 12345ieee** [comment]
Well, let's use `decode` only in the codepath that handles searching strings and leave `unicode_escape_decode` for the rest.

**Comment by 12345ieee** [comment]
So, without delving into the mess of python unicode support (where my knowledge is next to 0), could you at least merge the change at https://github.com/scanmem/scanmem/issues/172#issuecomment-225540990 ? Maybe leave a TODO saying to fix it for python3.

It completely fixes python2 (which is the default for any sane distro) and avoids `eval`ing user input.
Considering GC runs as root in the average user's machine, I'd really want to avoid GC running code by mistake:

    a\' if (1==2) else \'b

is an example of string that executes the not-extremely-dangerous `1==2`.

**Comment by sriemer** [comment]
Commit merged. I've put you as the author of the patch and wrote the commit description so that it counts as your contribution. Thanks!

**Comment by 12345ieee** [comment]
Great work with forging a commit from me (goes to explain why GPG-signing is a thing).
Should I change the title of the issue to say only python3 is affected now? Or open a new one?

**Comment by sriemer** [comment]
Nope, keep it as it is and let's handle the Python 3 part from now on. Of cause it may not break the Python 2 part. :wink:
