### ISSUE TITLE
GameConqueror: cannot select a process

### ISSUE THREAD

**Issue by luziferius** [scanmem/scanmem#328]
Selecting processes through the GUI is broken. If I click the select button, GameConqueror throws a ValueError, but nothing else happens.
Selecting a process by specifying the PID via command line argument works.

Reproducible: always
Version: `0.17-2`, installed from https://packages.ubuntu.com/bionic/gameconqueror

Steps to reproduce:
- Open GameConqueror
- Click on the `SelectProcess_Button`

Terminal output:
```
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 529, in SelectProcess_Button_clicked_cb
    pl = self.get_process_list()
  File "/usr/share/gameconqueror/GameConqueror.py", line 913, in get_process_list
    (pid, user, pname) = [tok.strip() for tok in proc.split(None, 2)]
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by sriemer** [comment]
Thanks for the bug report. I'll try to reproduce and check what's the issue. The packaging has been done for Debian 9 and just taken over by Ubuntu. I have to admit that I don't use GameConqueror for game cheating in "production" but use scanmem instead.

**Comment by luziferius** [comment]
I think I know why this happens.
I have the commercial [Teamviewer](https://www.teamviewer.com/) tool installed, which spawns some processes that don’t have a process name assigned. I can see that the `Command` column in `htop` is empty for some processes. If I execute `systemctl stop teamviewerd.service`, those disappear and GameConqueror starts working.

Thus, I conclude that `proc.split(None, 2)` happens to return only two values in this case. This breaks the tuple unpacking code.

**Comment by 12345ieee** [comment]
That's what you get for trying to parse a human readable output, well spotted.

@sriemer , I guess we fix it roughly as proposed by @luziferius , introducing a dependency on a real process utility library for python seems overkill.

**Comment by luziferius** [comment]
I found a better solution, than to just fill the missing values with with empty data.
You can resolve the symlink `/proc/pid/exe`, to get the process name:
```
if not pname:
    executable = pathlib.Path("/proc", pid, "exe")
    if executable.exists():
        pname = executable.resolve().name
```

**Comment by sriemer** [comment]
Test tool providing empty process name:
https://github.com/sriemer/spars-coding/tree/master/empty_proc

**Comment by sriemer** [comment]
Thanks, the idea to follow the `/proc/$pid/exe` symlink is a good one. But my suggestion is to keep using `os.path` for consistency. We want to do a bug fix in the end.

What about the following patch? @12345ieee, any objections?

```diff
diff --git a/gui/GameConqueror.py b/gui/GameConqueror.py
index 8f0b570891cd..3a9389b4119e 100644
--- a/gui/GameConqueror.py
+++ b/gui/GameConqueror.py
@@ -910,7 +910,15 @@ class GameConqueror():
     def get_process_list(self):
         plist = []
         for proc in os.popen('ps -wweo pid=,user:16=,command= --sort=-pid').readlines():
-            (pid, user, pname) = [tok.strip() for tok in proc.split(None, 2)]
+            try:
+                (pid, user, pname) = [tok.strip() for tok in proc.split(None, 2)]
+            except:
+                (pid, user) = [tok.strip() for tok in proc.split(None, 1)]
+                executable = os.path.join("/proc", pid, "exe")
+                if os.path.exists(executable):
+                    pname = os.path.realpath(executable)
+                else:
+                    pname = ''
             plist.append((int(pid), user, pname))
         return plist
 
```

**Comment by sriemer** [comment]
Maybe `exelink` is a better name than `executable` here. I'd like to switch to that name. Any objections?

**Comment by luziferius** [comment]
My only objection is: Don't use bare `except:`. Only catch the known ValueError.

And maybe add a comment line that explains why this is needed at all. The root cause is not immediately obvious here.

**Comment by 12345ieee** [comment]
Yeah, the bulk of the fix is fine but I also agree with both of @luziferius 's points.

**Comment by sriemer** [comment]
I'm way better with GNU C and the `scanmem` command line tool has way less bugs. :stuck_out_tongue:
Should be correct now. @12345ieee Please merge the PR. TIA

**Comment by sriemer** [comment]
TODO: Add the patch to the Debian package on salsa and involve @kartikm for queuing the fix or releasing a possible update. Also add the fix to my OBS home for openSUSE. Push `v0.17` fixes used in distro packages to `0.17.y` branch.
