### ISSUE TITLE
GameConqueror crashes on launch

### ISSUE THREAD

**Issue by PopeRigby** [scanmem/scanmem#399]
I get this error when running `gameconqueror` through my terminal:
```
/usr/share/gameconqueror/GameConqueror.py:1183: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/share/gameconqueror/GameConqueror.py:1184: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 1185, in <module>
    gc_instance = GameConqueror()
  File "/usr/share/gameconqueror/GameConqueror.py", line 323, in __init__
    self.backend = Scanmem(os.path.join(LIBDIR, 'libscanmem.so.1'))
  File "/usr/share/gameconqueror/scanmem.py", line 47, in __init__
    self._init_lib_functions()
  File "/usr/share/gameconqueror/scanmem.py", line 55, in _init_lib_functions
    f = getattr(self._lib, k)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libscanmem.so.1: undefined symbol: sm_process_is_dead
```

OS: Arch Linux
WM: Sway

**Comment by 12345ieee** [comment]
You're likely using a bleeding edge version of GC with an outdated version of libscanmem.
Either downgrade the former or upgrade the latter.

**Comment by PopeRigby** [comment]
That was the problem. Thank you.
