### ISSUE TITLE
GC errors on clipboard

### ISSUE THREAD

**Issue by Linrox** [scanmem/scanmem#435]
Trying to run game conqueror errors 

`Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 54, in <module>
    CLIPBOARD = Gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)
  File "/usr/lib64/python2.7/site-packages/gi/module.py", line 132, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gdk' object has no attribute 'SELECTION_CLIPBOARD'
`
Not sure if GC will work for leap 15.4. Scanmem works without issue.

**Comment by 1rhino2** [comment]
that traceback is python 2, the path gives it away:

```
File "/usr/lib64/python2.7/site-packages/gi/module.py", line 132, in __getattr__
AttributeError: 'gi.repository.Gdk' object has no attribute 'SELECTION_CLIPBOARD'
```

gameconqueror shipped a `#!/usr/bin/env python` shebang, so on a box where `python` still pointed at 2.7 it got launched under py2 and the gi bindings there do not expose that constant. the clipboard line is not actually wrong.

#457 changes the shebang to python3 and makes the launcher invoke python3 explicitly rather than trusting whatever `python` resolves to, which should sort this. same change fixes #438, which is the other side of the same coin, boxes with no `python` at all.

leaving this open rather than closing it on a guess, i do not have a leap 15.4 box to confirm on. if you are still around, retesting once 0.18.0 is tagged would be useful. separately, the "scanmem keeps asking for PID without progressing" at the end of your report is unrelated to the clipboard crash, that is usually the attach failing, and #459 just landed so the error will now tell you which of the two causes it actually is.
