### ISSUE TITLE
GUI won't start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#77]
```
What steps will reproduce the problem?
1. compile and install scanmem & GameConqueror from svn or git
2. run GameConqueror
3. enjoy the error message (if you have Python 3 as default)

What is the expected output? What do you see instead?
Expected: GUI
What I get:
** (GameConqueror.py:20621): WARNING **: Can't load fallback CSS resource: 
Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does 
not exist

** (GameConqueror.py:20621): WARNING **: Can't load fallback CSS resource: 
Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does 
not exist
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 1029, in <module>
    GameConqueror().main()
  File "/usr/share/gameconqueror/GameConqueror.py", line 318, in __init__
    self.backend = GameConquerorBackend()
  File "/usr/share/gameconqueror/backend.py", line 43, in __init__
    self.send_command('reset')
  File "/usr/share/gameconqueror/backend.py", line 67, in send_command
    self.lib.backend_exec_cmd(ctypes.c_char_p(cmd))
TypeError: bytes or integer address expected instead of str instance


What version of the product are you using? On what operating system?
I have tried both svn and git versions. I'm running Manjaro Linux (x64 
OpenBox). Python 3 is the default, which seems to be the problem.

Please provide any additional information below.
Runs fine if using Python 2 (python2 command instead of python).

```

Original issue reported on code.google.com by `valeri.g...@gmail.com` on 23 Aug 2014 at 11:24

**Comment by sriemer** [comment]
I can confirm that with python 3.4. I'm looking for a solution. Ideas welcome as I'm not best in python.

**Comment by sriemer** [comment]
The fixes have been merged, hence closing.
